### ISSUE TITLE
HRIR filtering files

### ISSUE THREAD

**Issue by renaudfv** [polarch/JSAmbisonics#12]
Hey,

I'm extending the HOA player to support ambisonics + stereo as a standalone player. From what I understand, the specified filter HRIR file path is appended with **_01_08ch.wav** and **_09_16ch.wav**. I am currently using the _HOA3_IRC_1008_virtual_ files featured in your examples, but is there any ressources or sources for other files. 

The audio I am featuring is excerpts or mixes featured on VR experiences, it therefore needs the minimal amount of coloration or effect on overall loudness. Trying out different filtering files would be quite useful. I'm aware IRCAM has open HRTF files, but am not able to find HRIR in the same format as you have.

Thank you!

**Comment by polarch** [comment]
Hi Renaud, the idea of the library was to give the opportunity for the user to use their own optimized/preferred ambisonic decoding filters. The ones included are there as reasonable examples. The format is one filter per ambisonic channel, resulting in (N+1)^2 filters for the left ear. The filtering for the right ear is done internally.  Many players use 2 times those filters (one set per ear), which is a minus in my opinion and increases computations without improving quality (the only reason to do that is if you have personalized HRTFs). 

Since many users won't have access to decoding filters but possibly to some publicly available HRTF set, I understant it would be useful to be able to generate these filters using the library - this is what the SOFA integration part is for, it works but it still needs some final work (on converting .sofa files to .json). Otherwise we have provided tools to convert these offline, using Matlab/Octave. Again generation of these decoding filters is not trivial, and I don't know of any other ambisonic library or player at the moment that provides some way for the user to do it.

So to answer your question finally :-), if you have a set of HRTFs that you are using for your project, you can a) try to convert them using Matlab or Octave using the provided scripts, if you are familiar with it, b) if the HRTFs are in SOFA format, try to convert them to .json and use the internal filter generator, c) send them to me and I can return you the decoding filters for some order that you want.

By the way, there are multiple available HRTF databases. However, HRTFs colour the sound by default, they need special pre-processing for minimzation of colouration at the expense of sharp localization. Let us know what you need specifically and we may be able to give you some more specific tips.

**Comment by renaudfv** [comment]
Alright, thanks for the feedback. I've read your paper on the lib and the AES SOFA specification paper. I think the best approach for me would be to find the HRTF set used to render the original content, convert it to SOFA and then to json. 

And for a quick question concerning the implementation; does the use of HRIR as wav files and SOFA as JSON is made because of the limitation of JavaScript file handling ? Also, are the HRIR impulse .wav files actually derived from HRTFs or are they the original impulse responses recorded ?

Thanks again!

**Comment by polarch** [comment]
Yep that sounds good. I know of the Matlab tools to read & manipulate SOFA files, given by the SOFA developers. But the format is NetCDF, and I noticed that there is a netcdf package in NPM to read such files, so I expect it would be possible in Node/browser.

About your question, most people will have access to some HRTFs and most likely in .wav format, from which they can derive the ambisonic2binaural decoding filters, also in .wav format (e.g. using the matlab tools). Or maybe they get a set of such filters from another decoder, software, platform, university, etc.. These can be re-used and loaded in the library directly, as .wav files.

SOFA is new, and since it contains also the metadata, such as HRTF measurement directions in a single file, it can be used directly to generate the decoding filters on-the-fly. Ideally the library would load the sofa files directly, but since we were using IRCAM's functions to read the HRIR for a certain value, these require the conversion to .json. In the future this dependency will be dropped and the .sofa files should be handled directly.
